/*
** ###################################################################
**
**     Copyright (c) 2016 Freescale Semiconductor, Inc.
**     Copyright 2017-2018 NXP
**
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**
**     o Neither the name of the copyright holder nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**
**
** ###################################################################
*/

/*==========================================================================*/
/*!
 * @file
 *
 * Header file containing the entry points and debug resource strings
 * for the HSLSIO subsystem.
 *
 * @addtogroup HSLSIO_SS
 * @{
 */
/*==========================================================================*/

/* DO NOT EDIT - This file auto generated by bin/config_ss_h.pl */

#ifndef SC_SS_HSLSIO_CONFIG_H
#define SC_SS_HSLSIO_CONFIG_H

/*!
 * This define defines the number of resources.
 */
#define SS_NUM_RSRC_HSLSIO 86U

/*! Define used to create subsystem function prototypes */
#define SS_FUNC_PROTO_HSLSIO \
    void ss_init_hslsio(sc_sub_t ss, sc_bool_t api_phase); \
    void ss_prepost_power_mode_hslsio(sc_sub_t ss, dsc_pdom_t pd, \
        ss_prepost_t type, sc_pm_power_mode_t from_mode, sc_pm_power_mode_t \
        to_mode, sc_bool_t rom_boot); \
    void ss_rdc_set_master_hslsio(sc_sub_t ss, ss_idx_t ss_idx, ss_ridx_t \
        rsrc_idx, sc_bool_t valid, sc_bool_t lock, sc_rm_spa_t sa, \
        sc_rm_spa_t pa, sc_rm_did_t did, sc_rm_sid_t sid, uint8_t cid); \
    sc_err_t ss_set_control_hslsio(sc_sub_t ss, ss_idx_t ss_idx, ss_ridx_t \
        rsrc_idx, uint32_t ctrl, uint32_t val); \
    sc_err_t ss_irq_enable_hslsio(sc_sub_t ss, ss_idx_t ss_idx, ss_ridx_t \
        rsrc_idx, sc_irq_group_t group, uint32_t mask, sc_bool_t enable); \
    sc_err_t ss_irq_status_hslsio(sc_sub_t ss, ss_idx_t ss_idx, ss_ridx_t \
        rsrc_idx, sc_irq_group_t group, uint32_t *status); \
    sc_err_t ss_irq_trigger_hslsio(sc_sub_t ss, sc_irq_group_t group, \
        uint32_t irq); \


/*!
 * This define is used to override the default SS function entry points.
 * If this isn't defined, then the SS uses functions in base.
 */
#define SS_EP_INIT_HSLSIO \
    { \
        ss_init_hslsio, \
        ss_trans_power_mode_base, \
        ss_set_cpu_power_mode_base, \
        ss_set_cpu_resume_base, \
        ss_req_sys_if_power_mode_base, \
        ss_updown_base, \
        ss_prepost_power_mode_hslsio, \
        ss_iso_disable_base, \
        ss_link_enable_base, \
        ss_ssi_power_base, \
        ss_ssi_bhole_mode_base, \
        ss_ssi_pause_mode_base, \
        ss_ssi_wait_idle_base, \
        ss_adb_enable_base, \
        ss_adb_wait_base, \
        ss_set_clock_rate_base, \
        ss_get_clock_rate_base, \
        ss_clock_enable_base, \
        ss_force_clock_enable_base, \
        ss_set_clock_parent_base, \
        ss_get_clock_parent_base, \
        ss_prepost_clock_mode_base, \
        ss_is_rsrc_accessible_base, \
        ss_cpu_start_base, \
        ss_rdc_enable_base, \
        ss_rdc_set_master_hslsio, \
        ss_rdc_set_peripheral_base, \
        ss_rdc_set_memory_base, \
        ss_rdc_is_did_vld_base, \
        ss_set_control_hslsio, \
        ss_get_control_base, \
        ss_irq_enable_hslsio, \
        ss_irq_status_hslsio, \
        ss_irq_trigger_hslsio, \
        ss_dump_base, \
    }

#ifdef DEBUG
    /*!
     * This define is used to name resources for debug output.
     */
    #define RNAME_INIT_HSLSIO_0 \
        "PWM_0", \
        "PWM_1", \
        "PWM_2", \
        "PWM_3", \
        "PWM_4", \
        "GPIO_0", \
        "GPIO_1", \
        "GPIO_2", \
        "GPIO_3", \
        "GPIO_4", \
        "GPIO_5", \
        "GPIO_6", \
        "FSPI_0", \
        "FSPI_1", \
        "GPT_0", \
        "GPT_1", \
        "GPT_2", \
        "GPT_3", \
        "GPT_4", \
        "KPP", \
        "MU_0A", \
        "MU_1A", \
        "MU_2A", \
        "MU_3A", \
        "MU_4A", \
        "MU_5A", \
        "MU_6A", \
        "MU_7A", \
        "MU_8A", \
        "MU_9A", \
        "MU_10A", \
        "MU_11A", \
        "MU_12A", \
        "MU_13A", \
        "MU_5B", \
        "MU_6B", \
        "MU_7B", \
        "MU_8B", \
        "MU_9B", \
        "MU_10B", \
        "MU_11B", \
        "MU_12B", \
        "MU_13B", \
        "IEE", \
        "IEE_R0", \
        "IEE_R1", \
        "IEE_R2", \
        "IEE_R3", \
        "IEE_R4", \
        "IEE_R5", \
        "IEE_R6", \
        "IEE_R7", \
        "OCRAM", \
        "PCIE_A", \
        "PCIE_B", \
        "SERDES_0", \
        "HSIO_GPIO", \
        "MATCH_0", \
        "MATCH_1", \
        "MATCH_2", \
        "MATCH_3", \
        "MATCH_4", \
        "MATCH_5", \
        "MATCH_6", \
        "MATCH_7", \
        "MATCH_8", \
        "MATCH_9", \
        "MATCH_10", \
        "MATCH_11", \
        "MATCH_12", \
        "MATCH_13", \
        "MATCH_14", \
        "MATCH_15", \
        "MATCH_16", \
        "MATCH_17", \
        "MATCH_18", \
        "MATCH_19", \
        "MATCH_20", \
        "MATCH_21", \
        "MATCH_22", \
        "MATCH_23", \
        "MATCH_24", \
        "MATCH_25", \
        "MATCH_26", \
        "MATCH_27", \
        "MATCH_28", \

#endif

#endif /* SC_SS_HSLSIO_CONFIG_H */

/**@}*/

