/*
** ###################################################################
**
**     Copyright (c) 2016 Freescale Semiconductor, Inc.
**     Copyright 2017-2018 NXP
**
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**
**     o Neither the name of the copyright holder nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**
**
** ###################################################################
*/

/*==========================================================================*/
/*!
 * @file
 *
 * Header file containing local resource defines for the HSLSIO subsystem.
 *
 * @addtogroup HSLSIO_SS
 * @{
 */
/*==========================================================================*/

/* DO NOT EDIT - This file auto generated by bin/rsrc_ss_h.pl */

#ifndef SC_SS_HSLSIO_RSRC_H
#define SC_SS_HSLSIO_RSRC_H

/*!
 * @name Defines for local SS resource indexes
 */
/*@{*/
#define SS_R_PWM_0               0U
#define SS_R_PWM_1               1U
#define SS_R_PWM_2               2U
#define SS_R_PWM_3               3U
#define SS_R_PWM_4               4U
#define SS_R_GPIO_0              5U
#define SS_R_GPIO_1              6U
#define SS_R_GPIO_2              7U
#define SS_R_GPIO_3              8U
#define SS_R_GPIO_4              9U
#define SS_R_GPIO_5              10U
#define SS_R_GPIO_6              11U
#define SS_R_FSPI_0              12U
#define SS_R_FSPI_1              13U
#define SS_R_GPT_0               14U
#define SS_R_GPT_1               15U
#define SS_R_GPT_2               16U
#define SS_R_GPT_3               17U
#define SS_R_GPT_4               18U
#define SS_R_KPP                 19U
#define SS_R_MU_0A               20U
#define SS_R_MU_1A               21U
#define SS_R_MU_2A               22U
#define SS_R_MU_3A               23U
#define SS_R_MU_4A               24U
#define SS_R_MU_5A               25U
#define SS_R_MU_6A               26U
#define SS_R_MU_7A               27U
#define SS_R_MU_8A               28U
#define SS_R_MU_9A               29U
#define SS_R_MU_10A              30U
#define SS_R_MU_11A              31U
#define SS_R_MU_12A              32U
#define SS_R_MU_13A              33U
#define SS_R_MU_5B               34U
#define SS_R_MU_6B               35U
#define SS_R_MU_7B               36U
#define SS_R_MU_8B               37U
#define SS_R_MU_9B               38U
#define SS_R_MU_10B              39U
#define SS_R_MU_11B              40U
#define SS_R_MU_12B              41U
#define SS_R_MU_13B              42U
#define SS_R_IEE                 43U
#define SS_R_IEE_R0              44U
#define SS_R_IEE_R1              45U
#define SS_R_IEE_R2              46U
#define SS_R_IEE_R3              47U
#define SS_R_IEE_R4              48U
#define SS_R_IEE_R5              49U
#define SS_R_IEE_R6              50U
#define SS_R_IEE_R7              51U
#define SS_R_OCRAM               52U
#define SS_R_PCIE_A              53U
#define SS_R_PCIE_B              54U
#define SS_R_SERDES_0            55U
#define SS_R_HSIO_GPIO           56U
#define SS_R_MATCH_0             57U
#define SS_R_MATCH_1             58U
#define SS_R_MATCH_2             59U
#define SS_R_MATCH_3             60U
#define SS_R_MATCH_4             61U
#define SS_R_MATCH_5             62U
#define SS_R_MATCH_6             63U
#define SS_R_MATCH_7             64U
#define SS_R_MATCH_8             65U
#define SS_R_MATCH_9             66U
#define SS_R_MATCH_10            67U
#define SS_R_MATCH_11            68U
#define SS_R_MATCH_12            69U
#define SS_R_MATCH_13            70U
#define SS_R_MATCH_14            71U
#define SS_R_MATCH_15            72U
#define SS_R_MATCH_16            73U
#define SS_R_MATCH_17            74U
#define SS_R_MATCH_18            75U
#define SS_R_MATCH_19            76U
#define SS_R_MATCH_20            77U
#define SS_R_MATCH_21            78U
#define SS_R_MATCH_22            79U
#define SS_R_MATCH_23            80U
#define SS_R_MATCH_24            81U
#define SS_R_MATCH_25            82U
#define SS_R_MATCH_26            83U
#define SS_R_MATCH_27            84U
#define SS_R_MATCH_28            85U
/*@}*/

#endif /* SC_SS_HSLSIO_RSRC_H */

/**@}*/

